# log level: none debug info error
log.level=info
draw.debug=false
opening.logo=true
opening.logo.fadeIn=0.8
opening.logo.fadeHold=1.5
opening.logo.fadeOut=0.6
opening.animation.duration=3
# 驴消耗配置
donkey.base.consumption=0.1
donkey.consumption.per.donkey=0.008
